data:
  path: "data"
  sample_rate: 8000
  train_folds: [1]
  val_folds: [2]
  test_folds: [3]
  batch_size: 8

model:
  base_filters: 32
  num_classes: 50
  optim:
    lr: 3e-4

trainer:
  gpus: 0
  max_epochs: 10

seed: 0
   
   
